# Generated by Django 4.0.4 on 2022-05-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
