# Generated by Django 4.0.4 on 2022-05-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
