# Generated by Django 4.0.4 on 2022-05-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialApp.user')),
            ],
        ),
    ]
