# Generated by Django 4.0.4 on 2022-05-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post2',
        ),
    ]
