# Generated by Django 4.0.4 on 2022-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.CharField(max_length=100),
        ),
    ]
